### ISSUE TITLE
I would like to push a branch...

### ISSUE THREAD

**Issue by Tigzy** [ssdeep-project/ssdeep#15]
With fixes for building on Windows.
How is that possible? Could you open pushing branches?

**Comment by a4lg** [comment]
That would be helpful but opening pushing a branch in [ssdeep-project/ssdeep] is not an option for us (for now).  How about making a pull request to publish your changes?

**Comment by Tigzy** [comment]
Well, how do I publich a PR without pushing a branch?

**Comment by a4lg** [comment]
I'm not y... okay.

1. Fork this repository.
2. Push your changes to *your* ssdeep repository.
3. GitHub asks you to make a pull request when you open ssdeep repository.

See some tutorials about GitHub for details.

**Comment by Tigzy** [comment]
https://github.com/ssdeep-project/ssdeep/pull/16

**Comment by Tigzy** [comment]
Could we reopen?

**Comment by a4lg** [comment]
No, we can just use #16 for further conversation.
