### ISSUE TITLE
Fuzzy Hash Image Comparison

### ISSUE THREAD

**Issue by FeraBellator** [ssdeep-project/ssdeep#17]
Hi,

I am in the process of completing an assignment for a University course and I am having issues comparing two images.

I am using a jpg image and changing the original by adding small text to the image.  Whenever, ssdeep in ran it comes back with a 0% match when only a small change has occurred.  My commands are:

ssdeep * > ss-hash-all-jpg.txt

ssdeep -a -m ss-hash-all-jpg.txt *

Can you please advise as to whether these commands are correct or whether there are any advanced commands I need to use? 

Thanks

FB

**Comment by jessek** [comment]
You didn't describe the type of changes you are making to these JPEG files, but I suspect you are changing how they look. Unfortunately, this is not how ssdeep works. ssdeep works by comparing the raw bytes, the ones and zeros, of the inputs. The program cannot compare how images look, their size, etc. You will need a different kind of program to compare how images appear.
