### ISSUE TITLE
SSDEEP down nothing wiht double-clicked in Windows 10

### ISSUE THREAD

**Issue by webzest** [ssdeep-project/ssdeep#32]
Hi,

I am working on a Python Machine Learning course and SSDEEP file comparison is one of the assigned tasks.

I downloaded the compiled binaries and unzipped the files on my Windows 10 system.  then, I double-clicked the files, but nothing happened.  just a blinking cursor on a black command prompt.  How do I use SSDEEP in windows for a python environment?

running PIP install SSDEEP in my env failed miserably.   How do I install ssdeep so it can work in python as an import ssdeep?

**Comment by jessek** [comment]
ssdeep is a command line program. It doesn't work by double-clicking it. You need to open a Command Prompt window and run ssdeep from there.
