### ISSUE TITLE
Fuzzy Hashing and Compare on GPU

### ISSUE THREAD

**Issue by ampangit** [ssdeep-project/ssdeep#37]
My python code that hashes/compares millions of data and takes a while to complete. We have installed an NVIDIA GPU and we want to utilise it to do the hashing and compare.

Some forums tell that ssdeep was designed to run on CPU. I have a doubt that this is true but can anyone here confirm thsi? Also, if there will be any suggestions on how i can utilize GPU?

Im not a pro in python.

**Comment by a4lg** [comment]
Hi.

Yes, ssdeep was designed to run on CPU (in fact, the original engine, spamsum, was created in 2002 and that's before the word GPGPU gets popular [around 2003-2004]).

My opinion is as follows:

*   Fuzzy hash generator is parallelizable when you process multiple streams at the same time but I don't think the algorithm can utilize the capabilities of GPU.
*   On the other hand, fuzzy hash comparison may utilize the capabilities of GPU, depending on the algorithm and the use case.

I hope it helps.
