### ISSUE TITLE
Can you please provide exact installation instructions on Windows?

### ISSUE THREAD

**Issue by emiliavanderwerf** [ssdeep-project/ssdeep#7]
When I issue the command `pip install ssdeep`, I receive the following error:

----- Installing 'ssdeep' -----
Collecting ssdeep
Using cached ssdeep-3.2.tar.gz
Complete output from command python setup.py egg_info:
running egg_info
creating pip-egg-info\ssdeep.egg-info
writing pip-egg-info\ssdeep.egg-info\PKG-INFO
writing dependency_links to pip-egg-info\ssdeep.egg-info\dependency_links.txt
writing requirements to pip-egg-info\ssdeep.egg-info\requires.txt
writing top-level names to pip-egg-info\ssdeep.egg-info\top_level.txt
writing manifest file 'pip-egg-info\ssdeep.egg-info\SOURCES.txt'
warning: manifest_maker: standard file '-c' not found
_ssdeep_cffi_b2f2ace7x627c7d55.c
ssdeep_pycache__ssdeep_cffi_b2f2ace7x627c7d55.c(213): **fatal error C1083: Cannot open include file: 'fuzzy.h': No such file or directory**
Traceback (most recent call last):
File "C:\Users\emili\AppData\Local\Programs\Python\Python36-32\lib\distutils_msvccompiler.py", line 423, in compile
self.spawn(args)
File "C:\Users\emili\AppData\Local\Programs\Python\Python36-32\lib\distutils_msvccompiler.py", line 542, in spawn
return super().spawn(cmd)
File "C:\Users\emili\AppData\Local\Programs\Python\Python36-32\lib\distutils\ccompiler.py", line 909, in spawn
spawn(cmd, dry_run=self.dry_run)
File "C:\Users\emili\AppData\Local\Programs\Python\Python36-32\lib\distutils\spawn.py", line 38, in spawn
_spawn_nt(cmd, search_path, dry_run=dry_run)
File "C:\Users\emili\AppData\Local\Programs\Python\Python36-32\lib\distutils\spawn.py", line 81, in _spawn_nt
"command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:
Program Files (x86)
Microsoft Visual Studio 14.0\\VC\\BIN
cl.exe' failed with exit status 2

Thanks!

**Comment by a4lg** [comment]
You are using PyPI package <https://pypi.python.org/pypi/ssdeep>, right?

If you want to use ssdeep as a command line application, you can just use prebuilt binary files from <https://github.com/ssdeep-project/ssdeep/releases>.

If you want to use ssdeep as a Python library, ... unfortunately, **ssdeep package on PyPI is not maintained by us** (it looks it uses version 2.13 of ssdeep). So the best solution would be asking PhiBo, the maintainer of ssdeep PyPI package. Considering the PyPI package source code (which uses GNU Autotools-based commands), it is natural that this package does not support Windows.

I apologize that I couldn't be helpful.
